name: Validate & Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  ENVIRONMENT: 'int'
  TEMPLATE_FILE: 'main'
  LOCATION: 'we'
  RESOURCE_GROUP: 'Test-Lab'

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    environment: int
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout
      - name: 1. Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # step 2: Auth with Azure
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # step 3: GitVersion
      - name: 2. Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: ./gitversion.yml
          
       # step 4: Replace tokens
      - name: Replace tokens
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@8e091844c27eb36853efbfade5ffca07260f0250
        uses: cschleiden/replace-tokens@v1.2
        with:
          files: parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam

       # step 5: what if deploy stage
      - name: What If Template deploy validation
        run: |
          az deployment group what-if --template-file ./templates/${{ env.TEMPLATE_FILE }}.bicep --parameters ./parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam --resource-group ${{ env.RESOURCE_GROUP }}
       
       # step 6: copy templates
      - name: Copy templates
        run: |
          mkdir -p ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/templates
          cp ./templates/${{ env.TEMPLATE_FILE }}.bicep ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/templates
            
       # step 7: copy parameters
      - name: Copy parameters
        run: |
          mkdir -p ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/parameters
          cp ./parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/parameters

        # step 8: publish the artifact
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact_${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}
          path: ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}
