name: Validate & Deploy
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  ENVIRONMENT: 'int'
  TEMPLATE_FILE: 'main'
  LOCATION: 'we'
  RESOURCE_GROUP: 'Test-Lab'


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout
      - name: 1. Checkout 
      - uses: actions/checkout@v3

      # step 2: GitVersion
      - name: 2. Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: gitversion.yml
          
       # step 3: Replace tokens
      - name: Replace tokens
        # You may pin to the exact commit or the version.
        # uses: cschleiden/replace-tokens@8e091844c27eb36853efbfade5ffca07260f0250
        uses: cschleiden/replace-tokens@v1.2
        with:
          files: parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam

       # step 4: what if deploy stage
      - name: What If Template deploy validation
        run: |
          az deployment group what-if --template-file .\templates\${{ env.TEMPLATE_FILE }}.bicep --parameters .\parameters\${{ env.ENVIRONMENT }}\${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam --resource-group ${{ env.RESOURCE_GROUP }}
       
       # step 5: copy templates
       # step 6: copy parameters
       
