# name: Validate & Deploy
# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
#   workflow_dispatch:

# env:
#   ENVIRONMENT: 'int'
#   TEMPLATE_FILE: 'main'
#   LOCATION: 'we'
#   RESOURCE_GROUP: 'Test-Lab'

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   validate:
#     environment: int
#     runs-on: ubuntu-latest
#     steps:
#     # Validation stage:
#       # step 1: checkout
#       - name: 1. Checkout 
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       # step 2: Auth with Azure
#       - name: Azure Login
#         uses: Azure/login@v1.4.6
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#       # step 3: GitVersion
#       - name: 2. Install GitVersion
#         uses: gittools/actions/gitversion/setup@v0
#         with:
#           versionSpec: '5.x'
#       - name: Determine Version
#         id: gitversion
#         uses: gittools/actions/gitversion/execute@v0
#         with:
#           useConfigFile: true
#           configFilePath: ./gitversion.yml
          
#        # step 4: Replace tokens
#       - name: Replace tokens
#         # You may pin to the exact commit or the version.
#         # uses: cschleiden/replace-tokens@8e091844c27eb36853efbfade5ffca07260f0250
#         uses: cschleiden/replace-tokens@v1.2
#         with:
#           files: parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam

#       #  # step 5: what if deploy stage
#       # - name: What If Template deploy validation
#       #   run: |
#       #     az deployment group what-if --template-file ./templates/${{ env.TEMPLATE_FILE }}.bicep --parameters ./parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam --resource-group ${{ env.RESOURCE_GROUP }}
       
#        # step 6: copy templates
#       - name: copy /templates/${{ env.TEMPLATE_FILE }}.bicep
#         run: |
#           mkdir -p ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/templates
#           ls -R ./templates # For debugging: List files in the templates directory
#           cp ./templates/${{ env.TEMPLATE_FILE }}.bicep ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/templates
#           ls -R ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/templates
#        # step 7: copy parameters
#       - name: Copy /parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam
#         run: |
#           mkdir -p ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/parameters
#           ls -R ./parameters/${{ env.ENVIRONMENT }} # For debugging: List files in the parameters directory
#           cp ./parameters/${{ env.ENVIRONMENT }}/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/parameters
#           ls -R ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/parameters

#        # step 8: publish the artifact
#       - name: Publish artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: artifact_${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}
#           path: ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}
#       #  # step 1: Checkout
#       # - name: 1. Checkout 
#       #   uses: actions/checkout@v3
#       #   with:
#       #     fetch-depth: 0

#       - name: List contents after upload
#         run: |
#           ls -R ${{ github.workspace }}/artifact/


#       - name: Adjust using directive in parameters file
#         run: |
#           ls -R ${{ github.workspace }}/artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}
#           sed -i 's|../../templates/main.bicep|${{ github.workspace }}/artifact/main_int_we/templates/main.bicep|' ./artifact/main_int_we/parameters/main_we.bicepparam
#           cat ./artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/parameters/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam

#       # - name: List contents of artifact directory
#       #   run: |
#       #     ls -R ./artifact/

#       - name: Adjust using directive in parameters file
#         run: |
#           # Move the files to the current directory
#           cp ./artifact/main_int_we/templates/main.bicep .
#           cp ./artifact/main_int_we/parameters/main_we.bicepparam .
#           # Update the reference in the parameter file
#           sed -i 's|/home/runner/work/networking/networking/artifact/main_int_we/templates/main.bicep|main.bicep|' main_we.bicepparam

#       - name: Deploy using the artifact
#         run: |
#           az deployment group create --template-file ./main.bicep --parameters ./main_we.bicepparam --resource-group ${{ env.RESOURCE_GROUP }}





# ### JUNK


#       # - name: Deploy using the artifact
#       #   run: |
#       #     az deployment group create --template-file ./artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/templates/${{ env.TEMPLATE_FILE }}.bicep --parameters ./artifact/${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}/parameters/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam --resource-group ${{ env.RESOURCE_GROUP }}


# #     # Deploy Stage
# #        # step 1: Checkout
# #       - name: 1. Checkout 
# #         uses: actions/checkout@v3
# #         with:
# #           fetch-depth: 0
# #       - name: Deploy ${{ env.TEMPLATE_FILE }}_${{ env.ENVIRONMENT }}_${{ env.LOCATION }}
# #         run: |
# #           pwd
# #           ls $GITHUB_WORKSPACE
# #           echo "$GITHUB_WORKSPACE"
# #           ls -al ./templates/main.bicep
# #           ls -al ./parameters/int/main_we.bicepparam
# #           ls -al /home/runner/work/networking/networking/artifact/main_int_we/templates
# #           ls -al /home/runner/work/networking/networking/artifact/main_int_we/parameters
# # #          az deployment group create --template-file  $GITHUB_WORKSPACE/templates/${{ env.TEMPLATE_FILE }}.bicep --parameters $GITHUB_WORKSPACE/parameters/${{ env.TEMPLATE_FILE }}_${{ env.LOCATION }}.bicepparam --resource-group ${{ env.RESOURCE_GROUP }}